Controllers/HerosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avengers.Models;

namespace Avengers.Controllers
{
    public class HerosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Heros
        public ActionResult Index()
        {
            var heros = db.Heros.Include(h => h.Civil);
            return View(heros.ToList());
        }

        // GET: Heros/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Heros heros = db.Heros.Include(s => s.Files).SingleOrDefault(s => s.HerosID == id);
            
            if (heros == null)
            {
                return HttpNotFound();
            }
            return View(heros);
        }

        // GET: Heros/Create
        public ActionResult Create()
        {
            ViewBag.HerosID = new SelectList(db.Civils, "CivilID", "NomComplet");
            return View();
        }

        // POST: Heros/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "HerosID,Pseudonyme,Telephone_Secret,Image_Heros,Disponible")] Heros heros, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var hero = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Hero,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        hero.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    heros.Files = new List<File> { hero };
                }
                db.Heros.Add(heros);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HerosID = new SelectList(db.Civils, "CivilID", "NomComplet", heros.HerosID);
            return View(heros);
        }

        // GET: Heros/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Heros heros = db.Heros.Include(s => s.Files).SingleOrDefault(s => s.HerosID == id);
            if (heros == null)
            {
                return HttpNotFound();
            }
            ViewBag.HerosID = new SelectList(db.Civils, "CivilID", "NomComplet", heros.HerosID);
            return View(heros);
        }

        // POST: Heros/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, HttpPostedFileBase upload)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var HeroUpdate = db.Heros.Find(id);
            if (TryUpdateModel(HeroUpdate, "",
                new string[] { "LastName", "FirstMidName", "EnrollmentDate" }))
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (HeroUpdate.Files.Any(f => f.FileType == FileType.Hero))
                        {
                            db.Files.Remove(HeroUpdate.Files.First(f => f.FileType == FileType.Hero));
                        }
                        var hero = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Hero,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            hero.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        HeroUpdate.Files = new List<File> { hero };
                    }
                    db.Entry(HeroUpdate).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(HeroUpdate);
        }

        // GET: Heros/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Heros heros = db.Heros.Find(id);
            if (heros == null)
            {
                return HttpNotFound();
            }
            return View(heros);
        }

        // POST: Heros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Heros heros = db.Heros.Find(id);
            db.Heros.Remove(heros);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PaysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avengers.Models;

namespace Avengers.Controllers
{
    public class PaysController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Pays
        public ActionResult Index()
        {
            return View(db.Pays.ToList());
        }

        // GET: Pays/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pays pays = db.Pays.Include(s => s.Files).SingleOrDefault(s => s.PaysID == id);
            
            if (pays == null)
            {
                return HttpNotFound();
            }
            return View(pays);
        }

        // GET: Pays/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pays/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PaysID,Pays_nom")] Pays pays, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var drapeau = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Drapeau,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        drapeau.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    pays.Files = new List<File> { drapeau };
                }
                db.Pays.Add(pays);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pays);
        }

        // GET: Pays/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pays pays = db.Pays.Include(s => s.Files).SingleOrDefault(s => s.PaysID == id);
            if (pays == null)
            {
                return HttpNotFound();
            }
            return View(pays);
        }

        // POST: Pays/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, HttpPostedFileBase upload)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var PaysUpdate = db.Pays.Find(id);
            if (TryUpdateModel(PaysUpdate, "",
                new string[] { "Pays_Nom"}))
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (PaysUpdate.Files.Any(f => f.FileType == FileType.Drapeau))
                        {
                            db.Files.Remove(PaysUpdate.Files.First(f => f.FileType == FileType.Drapeau));
                        }
                        var drapeau = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Drapeau,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            drapeau.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        PaysUpdate.Files = new List<File> { drapeau };
                    }
                    db.Entry(PaysUpdate).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(PaysUpdate);
        }

        // GET: Pays/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pays pays = db.Pays.Find(id);
            if (pays == null)
            {
                return HttpNotFound();
            }
            return View(pays);
        }

        // POST: Pays/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pays pays = db.Pays.Find(id);
            db.Pays.Remove(pays);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AVENGERS ALERT SYSTEM</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar  navbar-inverse   navbar-fixed-top">
        <div class="container ">
            <div class="navbar-header  ">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
                @Html.ActionLink("AVENGERS ALERT SYSTEM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                
                <ul class="nav navbar-nav">

                    <li><img src="https://i.ibb.co/d6qVZj5/unnamed.png" width="50" height="50"></li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            ADMINISTRATION
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">@Html.ActionLink("UTILISATEURS", "Index", "ApplicationUsers")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("ROLES", "Index", "CustomRoles")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("HABILITATIONS", "Index", "CustomUserRoles")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("PAYS", "Index", "Pays")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("CIVILS", "Index", "Civils")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("ORGANISATIONS", "Index", "Organisations")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("HEROS", "Index", "Heros")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("MECHANTS", "Index", "Mechants")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("MOTIFS INCIDENTS", "Index", "Incident_Motif")</a>

                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            MODERATION
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">@Html.ActionLink("INCIDENTS", "Index", "Incidents")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("MISSIONS", "Index", "Missions")</a>

                        </div>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            ACTIVITE HEROS
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">@Html.ActionLink("MISSIONS", "Index", "Missions")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("RAPPORTS MISSIONS", "Index", "RapportMissions")</a>


                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            SUIVI
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">@Html.ActionLink("SUIVI APRES INTERVENTIONS", "Index", "Satisfactions")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">@Html.ActionLink("DECLARER LITIGE", "Index", "Litiges")</a>


                        </div>
                    </li>

                    <li>@Html.ActionLink("CONTACT", "Contact", "Home")</li>






                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        
    </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AVENGERS ALERT SYSTEM</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>