Models/Incident.cs
using Avengers.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Avengers.Models
{
    public class Incident
    {

        [Key]
        public int IncidentID { get; set; }

        public int UserId { get; set; }


        [Display(Name = "Motif")]
        public int Incident_MotifID { get; set; }

        [Required]
        public int PaysID { get; set; }

        public string Contexte { get; set; }

        public string Adresse { get; set; }


        [DataType(DataType.Date)]
        public DateTime Date_Incident { get; set; }


        public virtual Incident_Motif Incident_Motif { get; set; }

        public virtual Pays Pays { get; set; }


        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<File> Files { get; set; }
    }
}

Controllers/IncidentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avengers.Models;

namespace Avengers.Controllers
{
    public class IncidentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Incidents
        public ActionResult Index()
        {
            var incidents = db.Incidents.Include(i => i.Incident_Motif).Include(i => i.Pays).Include(i => i.User);
            return View(incidents.ToList());
        }

        // GET: Incidents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Incident incident = db.Incidents.Include(s => s.Files).SingleOrDefault(s => s.IncidentID == id);
           
            if (incident == null)
            {
                return HttpNotFound();
            }
            return View(incident);
        }

        // GET: Incidents/Create
        public ActionResult Create()
        {
            ViewBag.Incident_MotifID = new SelectList(db.Incident_Motifs, "Incident_MotifID", "Motif");
            ViewBag.PaysID = new SelectList(db.Pays, "PaysID", "Pays_nom");
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Incidents/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IncidentID,UserId,Incident_MotifID,PaysID,Contexte,Adresse,Date_Incident")] Incident incident, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var photo = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Photo,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        photo.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    incident.Files = new List<File> { photo };
                }
                db.Incidents.Add(incident);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(incident);
        }

        // GET: Incidents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Incident incident = db.Incidents.Include(s => s.Files).SingleOrDefault(s => s.IncidentID == id);
            if (incident == null)
            {
                return HttpNotFound();
            }
            ViewBag.Incident_MotifID = new SelectList(db.Incident_Motifs, "Incident_MotifID", "Motif", incident.Incident_MotifID);
            ViewBag.PaysID = new SelectList(db.Pays, "PaysID", "Pays_nom", incident.PaysID);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", incident.UserId);
            return View(incident);
        }

        // POST: Incidents/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, HttpPostedFileBase upload)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var IncidentUpdate = db.Incidents.Find(id);
            if (TryUpdateModel(IncidentUpdate, "",
                new string[] { "Motif", "Pays", "Email","Contexte","Adresse","Date_Incident" }))
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (IncidentUpdate.Files.Any(f => f.FileType == FileType.Photo))
                        {
                            db.Files.Remove(IncidentUpdate.Files.First(f => f.FileType == FileType.Photo));
                        }
                        var photo = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Photo,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            photo.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        IncidentUpdate.Files = new List<File> { photo };
                    }
                    db.Entry(IncidentUpdate).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
                
            }
            return View(IncidentUpdate);
        }

        // GET: Incidents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Incident incident = db.Incidents.Find(id);
            if (incident == null)
            {
                return HttpNotFound();
            }
            return View(incident);
        }

        // POST: Incidents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Incident incident = db.Incidents.Find(id);
            db.Incidents.Remove(incident);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Incidents/Create.cshtml
@model Avengers.Models.Incident

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Incidents", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Incident</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Incident_MotifID, "Incident_MotifID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Incident_MotifID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Incident_MotifID, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Contexte, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contexte, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contexte, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PaysID, "PaysID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("PaysID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PaysID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Adresse, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Adresse, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date_Incident, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date_Incident, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date_Incident, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Photo", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="Photo" name="upload" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Incidents/Delete.cshtml
@model Avengers.Models.Incident

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Incident</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Incident_Motif.Motif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Incident_Motif.Motif)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pays.Pays_nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pays.Pays_nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contexte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contexte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Incident)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Incident)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Incidents/Details.cshtml
@model Avengers.Models.Incident

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Incident</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Incident_Motif.Motif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Incident_Motif.Motif)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pays.Pays_nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pays.Pays_nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contexte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contexte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Incident)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Incident)
        </dd>
        @if (Model.Incident_Motif.Files.Any(f => f.FileType == FileType.Photo))
        {
            <dt>
                Symbole
            </dt>
            <dd>
                <img src="~/File?id=@Model.Incident_Motif.Files.First(f => f.FileType == FileType.Photo).FileId" height="50" width="50" alt="symbole" />
            </dd>
        }
        @if (Model.Files.Any(f => f.FileType == FileType.Photo))
        {
            <dt>
                Photo de l'incident
            </dt>
            <dd>
                <img src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Photo).FileId" height="150" width="150" alt="photo" />
            </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IncidentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Incidents/Edit.cshtml
@model Avengers.Models.Incident

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Incidents", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Incident</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IncidentID)

    <div class="form-group">
        @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Incident_MotifID, "Incident_MotifID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Incident_MotifID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Incident_MotifID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PaysID, "PaysID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("PaysID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PaysID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Contexte, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Contexte, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Contexte, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Adresse, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Adresse, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Date_Incident, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date_Incident, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date_Incident, "", new { @class = "text-danger" })
        </div>
    </div>

    @if (Model.Files.Any(f => f.FileType == FileType.Photo))
    {
        <div class="form-group">
            <span class="control-label col-md-2"><strong>Photo de l'incident</strong></span>
            <div class="col-md-10">
                <img src="~/File?id=@Model.Files.First(f => f.FileType == FileType.Photo).FileId" height="150" width="150" alt="photo" />
            </div>
        </div>
    }

    <div class="form-group">
        @Html.Label("Photo", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="Photo" name="upload" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Incidents/Index.cshtml
@model IEnumerable<Avengers.Models.Incident>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Incident_Motif.Motif)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pays.Pays_nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contexte)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adresse)
        </th>
        <th>
               Photo de l'incident
        </th>
        <th>
            Symbole
            incident
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date_Incident)
        </th>
        <th>
           Créer Mission

        </th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Incident_Motif.Motif)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Pays.Pays_nom)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.User.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Contexte)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Adresse)
    </td>
    <td>
        <img src="~/File?id=@item.Files.First(f => f.FileType == Avengers.Models.FileType.Photo).FileId" height="50" width="50" alt="photo" />
    </td>
    <td>
        <img src="~/File?id=@item.Incident_Motif.Files.First(f => f.FileType == Avengers.Models.FileType.Symbole).FileId" height="50" width="50" alt="symbole" />
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Date_Incident)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.IncidentID }) |
        @Html.ActionLink("Details", "Details", new { id = item.IncidentID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.IncidentID })
    </td>
    <td>
        <p><a href="~/Missions/Create" class="btn btn-info active" role="button" aria-pressed="true">MISSION</a></p>
    </td>

</tr>
}

</table>